import type { TableNode, ERDEdge } from '@/types/erd';
import { extractColId } from '@/lib/handle-id';
import { DSL_TABLE_KEYWORD, DSL_COLUMN_OPTIONS } from '@/lib/dsl-keywords';

const [OPT_PK, OPT_AI, OPT_NN] = DSL_COLUMN_OPTIONS;

/** DSL 생성에 필요한 사전 역조회 인터페이스 */
export interface DslGeneratorDictionary {
  /** Term ID → Term 조회 */
  findTermById: (id: number) => { logicalName: string; domainId?: number | null } | undefined;
  /** Domain ID → Domain 조회 */
  findDomainById: (id: number) => { logicalName: string } | undefined;
}

/** FK 참조 정보 (논리명 기반) */
interface DslFkRef {
  /** 부모 테이블 논리명 */
  parentTableLogical: string;
  /** 부모 컬럼 논리명 */
  parentColLogical: string;
}

/**
 * 테이블 노드에서 표시용 논리명을 결정한다.
 *
 * 우선순위: logicalTableName → label(물리명)
 *
 * @param node 테이블 노드
 * @returns 테이블 논리명
 */
function resolveTableLogicalName(node: TableNode): string {
  return node.data.logicalTableName || node.data.label;
}

/**
 * ERD 노드/엣지를 논리명 DSL 텍스트로 변환한다.
 *
 * ddl-generator.ts와 대칭 구조로, ERD 상태를 논리명 DSL로 역변환한다.
 * 사전 역조회를 통해 Term/Domain의 논리명을 복원한다.
 *
 * @param nodes      React Flow 테이블 노드 배열
 * @param edges      React Flow 엣지 배열 (FK 관계)
 * @param dictionary 사전 역조회 인터페이스
 * @returns 논리명 DSL 텍스트
 */
export function generateDsl(
  nodes: TableNode[],
  edges: ERDEdge[],
  dictionary: DslGeneratorDictionary,
): string {
  if (nodes.length === 0) {
    return '';
  }

  // 노드 맵 구축: nodeId → TableNode
  const nodeMap = new Map<string, TableNode>();
  for (const node of nodes) {
    nodeMap.set(node.id, node);
  }

  // FK 맵 구축: "targetNodeId:targetColId" → DslFkRef
  const fkMap = new Map<string, DslFkRef>();
  for (const edge of edges) {
    if (!edge.sourceHandle || !edge.targetHandle) continue;

    const sourceNode = nodeMap.get(edge.source);
    const targetNode = nodeMap.get(edge.target);
    if (!sourceNode || !targetNode) continue;

    const sourceColId = extractColId(edge.sourceHandle, edge.source);
    const targetColId = extractColId(edge.targetHandle, edge.target);

    const sourceCol = sourceNode.data.columns.find((c) => c.id === sourceColId);
    const targetCol = targetNode.data.columns.find((c) => c.id === targetColId);

    if (sourceCol && targetCol) {
      const parentTableLogical = resolveTableLogicalName(sourceNode);
      const parentColLogical = sourceCol.logicalName || sourceCol.name;

      fkMap.set(`${edge.target}:${targetColId}`, {
        parentTableLogical,
        parentColLogical,
      });
    }
  }

  // 헤더 주석
  const now = new Date().toISOString().split('T')[0];
  const lines: string[] = [];
  lines.push(`// Generated by Smart ERD`);
  lines.push(`// Date: ${now}`);
  lines.push('');

  // 테이블 순회
  for (let i = 0; i < nodes.length; i++) {
    const node = nodes[i];
    const tableLogical = resolveTableLogicalName(node);

    lines.push(`${DSL_TABLE_KEYWORD} ${tableLogical} {`);

    for (const col of node.data.columns) {
      const colLogical = col.logicalName || col.name;

      const parts: string[] = [`  ${colLogical}`];

      // FK 참조
      const fkRef = fkMap.get(`${node.id}:${col.id}`);
      if (fkRef) {
        parts.push(`> ${fkRef.parentTableLogical}.${fkRef.parentColLogical}`);
      }

      // 도메인 명시 판정
      const domainLabel = resolveDomainLabel(col, dictionary);
      if (domainLabel) {
        parts.push(`:${domainLabel}`);
      } else {
        const typeLabel = resolveTypeLabel(col);
        if (typeLabel) {
          parts.push(`::${typeLabel}`);
        }
      }

      // 옵션
      const options = buildOptions(col);
      if (options) {
        parts.push(`[${options}]`);
      }

      lines.push(parts.join(' '));
    }

    lines.push('}');

    // 테이블 간 빈 줄
    if (i < nodes.length - 1) {
      lines.push('');
    }
  }

  return lines.join('\n') + '\n';
}

/**
 * 컬럼의 도메인 명시 여부를 판정하고, 명시할 도메인 논리명을 반환한다.
 *
 * - domainId가 있으면 항상 명시
 * - 그 외 → null (생략)
 *
 * @param col        컬럼 정보
 * @param dictionary 사전 역조회
 * @returns 도메인 논리명 또는 null
 */
function resolveDomainLabel(
  col: { termId?: number; domainId?: number },
  dictionary: DslGeneratorDictionary,
): string | null {
  if (col.domainId) {
    const domain = dictionary.findDomainById(col.domainId);
    return domain?.logicalName ?? null;
  }

  return null;
}

/** 도메인이 없는 컬럼의 타입 표현 문자열을 반환한다. */
function resolveTypeLabel(col: { domainId?: number; type?: string }): string | null {
  if (col.domainId) {
    return null;
  }
  const normalized = col.type?.trim();
  if (!normalized) {
    return null;
  }
  return normalized;
}

/**
 * 컬럼 옵션 문자열을 생성한다.
 *
 * @param col 컬럼 정보
 * @returns 옵션 문자열 (예: "PK, AI") 또는 빈 문자열
 */
function buildOptions(col: { pk?: boolean; autoIncrement?: boolean; nullable?: boolean }): string {
  const opts: string[] = [];
  if (col.pk) opts.push(OPT_PK);
  if (col.autoIncrement) opts.push(OPT_AI);
  if (!col.nullable && !col.pk) opts.push(OPT_NN);
  return opts.join(', ');
}
