services:
  postgres:
    image: 'postgres:17'
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: smarterd
      POSTGRES_USER: smarterd
      POSTGRES_PASSWORD: smarterd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      org.springframework.boot.service-connection: postgres

  redis:
    image: 'redis:7-alpine'
    container_name: smart-erd-redis
    ports:
      - '16379:6379'
    profiles:
      - redis
    labels:
      org.springframework.boot.service-connection: redis

volumes:
  postgres-data:
    name: smart-erd_postgres-data
