-- Phase 11: persisted AI action proposals

CREATE TABLE IF NOT EXISTS ai_action_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id VARCHAR(80) NOT NULL UNIQUE,
    execution_id VARCHAR(80) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    action_type VARCHAR(120) NOT NULL,
    risk_level VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    team_id BIGINT,
    project_id BIGINT,
    target_type VARCHAR(80),
    target_id VARCHAR(120),
    target_label VARCHAR(200),
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    requested_by VARCHAR(50) NOT NULL,
    decision_by VARCHAR(50),
    decided_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    sanitized_payload_json TEXT,
    preview_json TEXT,
    result_json TEXT,
    redacted_error_type VARCHAR(80),
    redacted_error_title VARCHAR(200),
    redacted_error_detail VARCHAR(500),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_ai_action_proposals_proposal_id
    ON ai_action_proposals (proposal_id);

CREATE INDEX IF NOT EXISTS idx_ai_action_proposals_execution_id
    ON ai_action_proposals (execution_id);

CREATE INDEX IF NOT EXISTS idx_ai_action_proposals_project
    ON ai_action_proposals (team_id, project_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_ai_action_proposals_requested_by
    ON ai_action_proposals (requested_by, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_ai_action_proposals_status_expiry
    ON ai_action_proposals (status, expires_at);
