-- User-specific UI personalization settings

CREATE TABLE IF NOT EXISTS user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    CONSTRAINT uk_user_settings_user_id_setting_key UNIQUE (user_id, setting_key)
);

CREATE INDEX IF NOT EXISTS idx_user_settings_user_id
    ON user_settings (user_id);
