-- Phase 10-A: WBS planning foundation (template / duplicate / bulk-create / shift)

ALTER TABLE wbs_items DROP CONSTRAINT IF EXISTS chk_wbs_items_depth;
ALTER TABLE wbs_items
    ADD CONSTRAINT chk_wbs_items_depth CHECK (depth BETWEEN 0 AND 8);

CREATE TABLE IF NOT EXISTS wbs_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    root_name VARCHAR(200) NOT NULL,
    item_count INTEGER NOT NULL,
    dependency_count INTEGER NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_wbs_templates_project_updated
    ON wbs_templates (project_id, updated_at DESC, id DESC);
