-- Phase 8-4: project issue tracker schema

CREATE TABLE IF NOT EXISTS project_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    assignee_user_id BIGINT REFERENCES users(id),
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    CONSTRAINT chk_project_issues_status CHECK (status IN ('REGISTERED', 'IN_PROGRESS', 'DONE')),
    CONSTRAINT chk_project_issues_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT chk_project_issues_title_not_blank CHECK (char_length(btrim(title)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_project_issues_project_filters
    ON project_issues (project_id, status, priority, assignee_user_id);

CREATE INDEX IF NOT EXISTS idx_project_issues_project_updated_at
    ON project_issues (project_id, updated_at, created_at, id);
