-- Phase 9-A: WBS dependency schema

CREATE TABLE IF NOT EXISTS wbs_dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    predecessor_wbs_item_id BIGINT NOT NULL REFERENCES wbs_items(id) ON DELETE CASCADE,
    successor_wbs_item_id BIGINT NOT NULL REFERENCES wbs_items(id) ON DELETE CASCADE,
    dependency_type VARCHAR(10) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    CONSTRAINT uq_wbs_dependencies_edge_type UNIQUE (
        project_id,
        predecessor_wbs_item_id,
        successor_wbs_item_id,
        dependency_type
    ),
    CONSTRAINT chk_wbs_dependencies_not_self CHECK (predecessor_wbs_item_id <> successor_wbs_item_id)
);

CREATE INDEX IF NOT EXISTS idx_wbs_dependencies_project_sort
    ON wbs_dependencies (project_id, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_wbs_dependencies_predecessor
    ON wbs_dependencies (predecessor_wbs_item_id);

CREATE INDEX IF NOT EXISTS idx_wbs_dependencies_successor
    ON wbs_dependencies (successor_wbs_item_id);
