-- Phase 8-1 Stage 2: shared work comments and activity history

CREATE TABLE IF NOT EXISTS work_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_work_comments_target
    ON work_comments (project_id, target_type, target_id, created_at, id);

CREATE TABLE IF NOT EXISTS work_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    subject_type VARCHAR(30),
    subject_id BIGINT,
    subject_label VARCHAR(200),
    previous_value VARCHAR(100),
    current_value VARCHAR(100),
    detail VARCHAR(500),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_work_activities_target
    ON work_activities (project_id, target_type, target_id, created_at DESC, id DESC);
