-- Phase 7-01: project staffing schema

CREATE TABLE IF NOT EXISTS project_staffing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    grade VARCHAR(20) NOT NULL,
    monthly_rate BIGINT NOT NULL,
    planned_start_date DATE NOT NULL,
    planned_end_date DATE NOT NULL,
    planned_participation_rate INTEGER NOT NULL,
    actual_start_date DATE,
    actual_end_date DATE,
    actual_participation_rate INTEGER,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    CONSTRAINT uk_project_staffing_project_user UNIQUE (project_id, user_id),
    CONSTRAINT chk_project_staffing_grade CHECK (grade IN ('JUNIOR', 'MIDDLE', 'SENIOR', 'EXPERT')),
    CONSTRAINT chk_project_staffing_monthly_rate CHECK (monthly_rate >= 0 AND monthly_rate <= 999999999),
    CONSTRAINT chk_project_staffing_planned_period CHECK (planned_start_date <= planned_end_date),
    CONSTRAINT chk_project_staffing_planned_participation CHECK (planned_participation_rate BETWEEN 0 AND 100),
    CONSTRAINT chk_project_staffing_actual_participation CHECK (
        actual_participation_rate IS NULL OR actual_participation_rate BETWEEN 0 AND 100
    ),
    CONSTRAINT chk_project_staffing_actual_fields CHECK (
        (
            actual_start_date IS NULL
            AND actual_end_date IS NULL
            AND actual_participation_rate IS NULL
        )
        OR (
            actual_start_date IS NOT NULL
            AND actual_end_date IS NOT NULL
            AND actual_participation_rate IS NOT NULL
            AND actual_start_date <= actual_end_date
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_project_staffing_project_user
    ON project_staffing (project_id, user_id);

CREATE INDEX IF NOT EXISTS idx_project_staffing_project_grade
    ON project_staffing (project_id, grade);

CREATE INDEX IF NOT EXISTS idx_project_staffing_project_planned_period
    ON project_staffing (project_id, planned_start_date, planned_end_date);
