-- Phase 8-1 Stage 1: WBS document link schema

CREATE TABLE IF NOT EXISTS wbs_document_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wbs_item_id BIGINT NOT NULL REFERENCES wbs_items(id) ON DELETE CASCADE,
    diagram_id BIGINT NOT NULL REFERENCES diagrams(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    CONSTRAINT uq_wbs_document_links UNIQUE (wbs_item_id, diagram_id)
);

CREATE INDEX IF NOT EXISTS idx_wbs_document_links_wbs_item
    ON wbs_document_links (wbs_item_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_wbs_document_links_diagram
    ON wbs_document_links (diagram_id);
