-- Phase 5-01: WBS + Milestone 스키마

CREATE TABLE IF NOT EXISTS milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    target_date DATE NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_milestones_project_sort
    ON milestones (project_id, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_milestones_project_target_date
    ON milestones (project_id, target_date);

CREATE TABLE IF NOT EXISTS wbs_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES wbs_items(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    depth INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    assignee_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    start_date DATE,
    end_date DATE,
    progress_rate INTEGER NOT NULL DEFAULT 0,
    estimated_mm NUMERIC(6,2),
    milestone_id BIGINT REFERENCES milestones(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    CONSTRAINT chk_wbs_items_depth CHECK (depth BETWEEN 0 AND 2),
    CONSTRAINT chk_wbs_items_progress_rate CHECK (progress_rate BETWEEN 0 AND 100),
    CONSTRAINT chk_wbs_items_estimated_mm CHECK (estimated_mm IS NULL OR estimated_mm >= 0),
    CONSTRAINT chk_wbs_items_period CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date)
);

CREATE INDEX IF NOT EXISTS idx_wbs_items_project_parent_sort
    ON wbs_items (project_id, parent_id, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_wbs_items_project_milestone
    ON wbs_items (project_id, milestone_id);

CREATE INDEX IF NOT EXISTS idx_wbs_items_assignee
    ON wbs_items (assignee_user_id);
