-- Phase 8-1 Stage 3: personal TODO domain and document links

CREATE TABLE IF NOT EXISTS project_todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    linked_wbs_item_id BIGINT REFERENCES wbs_items(id) ON DELETE SET NULL,
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    target_date DATE,
    progress_rate INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_project_todos_owner
    ON project_todos (project_id, owner_user_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_project_todos_wbs
    ON project_todos (project_id, linked_wbs_item_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS todo_document_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL REFERENCES project_todos(id) ON DELETE CASCADE,
    diagram_id BIGINT NOT NULL REFERENCES diagrams(id) ON DELETE CASCADE,
    visibility VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    CONSTRAINT uq_todo_document_links UNIQUE (todo_id, diagram_id)
);

CREATE INDEX IF NOT EXISTS idx_todo_document_links_todo
    ON todo_document_links (todo_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_todo_document_links_diagram
    ON todo_document_links (diagram_id);
