-- Phase 9: metadata-only AI execution audit

CREATE TABLE IF NOT EXISTS ai_execution_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id VARCHAR(80) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    status VARCHAR(30) NOT NULL,
    availability_status VARCHAR(50),
    error_type VARCHAR(80),
    duration_ms BIGINT,
    requested_by VARCHAR(50) NOT NULL,
    team_id BIGINT,
    project_id BIGINT,
    redacted_error_title VARCHAR(200),
    redacted_error_detail VARCHAR(500),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS idx_ai_execution_audits_execution_id
    ON ai_execution_audits (execution_id);

CREATE INDEX IF NOT EXISTS idx_ai_execution_audits_project
    ON ai_execution_audits (team_id, project_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_ai_execution_audits_requested_by
    ON ai_execution_audits (requested_by, created_at DESC, id DESC);
